spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: root
    url: jdbc:h2:mem:springBootCrudApi
    username: root
    

  jpa:
    hibernate:
      ddl-auto: create
      
    show-sql: true
  h2:
    console:
      enabled: true


 